[project]
name = "sk-orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "mcp>=1.5.0",
    "openai>=1.68.2",
    "python-dotenv>=1.1.0",
    "semantic-kernel>=1.26.1",
]
